# type `egrecho train-asv -h` to show help
save_dir: ???
seed_everything: 42
data_builder:
  class_path: ASVPipeBuilder
  init_args:
    config:
      class_path: ASVBuilderConfig
      init_args:
        data_dir: exp/egs
        file_patterns:
          train:
          - aishell1_3_aidatatang200_shard/egs*train*
          - cn_16k_7700h_shard/egs*train*
          - voxceleb2_dev1k_ssd/egs*train*
          val:
          - aishell1_3_aidatatang200_shard/egs*val*
          - cn_16k_7700h_shard/egs*val*
          - voxceleb2_dev1k_ssd/egs*val*
        data_type: shard
        shuffle: true
        partition: true
        label_fname:
          - aishell1_3_aidatatang200_shard/speaker.yaml
          - cn_16k_7700h_shard/speaker.yaml
          - voxceleb2_dev1k_ssd/speaker.yaml
        filter_conf:
          max_length: 15.
          min_length: 2.
          truncate: true
        resample_rate: 8000
        pre_sp_factors:
        - 0.9
        - 1.0
        - 1.1
        rand_chunksize: 300
        chunk_retry_param:
          retry: 2
        frame_shift: 0.01
        speech_aug: true
        speech_aug_config:
          batch_size: 1
          db_dir: /work/ldx/speech_aug  # replace your noise set
          init_p: 0.5
          # sim_rir_prob: 0.5
          wave_drop: true
          drop_time_count: [0, 4]
        a_law_sim: false
        shard_shuffle_size: 1500
        batch_size: 128
        drop_last: true
        extractor_param:
          scale_bit: null
          feat_conf:
            feature_type: fbank
            window_type: 'povey'
            low_freq: 20
            high_freq: 0
            energy_floor: 1
          sampling_rate: 8000  # torchaudio feat_conf refuse sr, set it here
          mean_norm: true
          std_norm: false
data_attrs:
- inputs_dim
- num_classes
data:
  num_workers: 8
  prefetch_factor: 20
  val_num_workers: 0
  pin_memory: false
  fullsync: true
run:
  model:  # can replace a config yaml here
    class_path: WeSpkModel
    init_args:
      config:
        class_path: WeSpkSVConfig
        init_args:
          init_model_id: campplus
          num_classes: 2
          classifier_str: aam
          classifier_params:
            sub_k: 1
            do_topk: false
  resume_ckpt: null
  teacher:
    class_path: SVTeacher
    init_args:
      num_classes: null
      margin_warm: true
      margin_warm_kwargs:
        start_epoch: 5
        end_epoch: 10
      optimizer:
      - sgd
      - weight_decay: 1e-4
        momentum: 0.9
        nesterov: true
      lr_scheduler:
      - warm_cosine
      - warmup_steps: 0.1
        # pct_start: 0.1
        eta_min: 1e-6
      lr: 0.01
  trainer:
    accelerator: gpu
    strategy: auto
    devices: 4
    precision: 16-mixed
    fast_dev_run: false
    max_epochs: 30
    limit_val_batches: null
    val_check_interval: 3000
    check_val_every_n_epoch: 1
    num_sanity_val_steps: null
    log_every_n_steps: 500
    accumulate_grad_batches: 1
    gradient_clip_val: 5.0
    gradient_clip_algorithm: norm
    deterministic: null
    benchmark: true
    inference_mode: true
    profiler: null
    sync_batchnorm: true
  mckpt:
    dirpath: null
    filename: epoch{epoch}-val_loss{val_loss:.2f}-step{step:.2e}
    monitor: val_loss
    save_last: true
    save_top_k: 10
    mode: min
    auto_insert_metric_name: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: 1
    save_on_train_epoch_end: true
  use_early_stopping: false
  early_stopping:
    monitor: val_loss
    min_delta: 0.0
    patience: 10
    mode: min
    check_on_train_epoch_end: true
    log_rank_zero_only: true
