manifest_dir: miss
prefix_name: aishell_vi
suffix: jsonl.gz
max_cuts: 16
bucketing_sampler: true
num_buckets: 30
concatenate_cuts: false
duration_factor: 1.0
gap: 1.0
on_the_fly_feats: false
shuffle: true
num_workers: 2
enable_spec_aug: true
spec_aug_time_warp_factor: 80
enable_musan: true
base_model: miss
output_dir: miss
optim: adamw_torch
lion_beta1: 0.016
lr_scheduler_type: constant_with_warmup
num_train_epochs: 3
max_steps: -1
freeze_encoder: false
warmup_steps: 1000
logging_steps: 100
eval_steps: 2500
save_steps: 5000
learning_rate: 1.0e-05
fp16: true
local_files_only: true
language: Chinese
task: transcribe
use_fast_tokenizer: true
resume_from_checkpoint: null
gradient_accumulation_steps: 1
gradient_checkpointing: false
max_grad_norm: 5.0
remove_whisper_encoder_input_length_restriction: false
empty_init: true
deepspeed:  config/ds_config_z2.json
